### PR TITLE
Update circular_percent_indicator.dart

### PR DESCRIPTION
**Pull request by superciccio**
option to restart the animation when reached the end

### CODE REVIEW

**Comment by diegoveloper** [comment]
hey, thanks for the PR, can you point to `dev` branch instead of `master` ? don't forget to run `dartfmt`

**Comment by superciccio** [comment]
> hey, thanks for the PR, can you point to `dev` branch instead of `master` ? don't forget to run `dartfmt`

done !

**Comment by diegoveloper** [comment]
thanks!

**Comment by diegoveloper** [comment]
@superciccio could you add the same for `LinearPercentIndicator` ?  D

**Pull request merged**
