### PR TITLE
Rollback WidgetsBinding.instance null-aware operator for Flutter 2.10 or earlier.

### PR DESCRIPTION
**Pull request by masahiro-ikemoto**
Rollback WidgetsBinding.instance null-aware operator and bump the version to lock by Flutter 2.10.

### CODE REVIEW

**Review by diegoveloper — APPROVED** [review]
thank you

**Comment by masahiro-ikemoto** [comment]
Sorry! I have misstype for null-aware op. place.
```
WidgetsBinding?.instance.addPostFrameCallback
```
v
```
WidgetsBinding.instance?.addPostFrameCallback
```

Could you please re-release?

If necessary, I create the PR again.

**Comment by diegoveloper** [comment]
I think you can point to the older version, I'm tired of doing this.

**Comment by masahiro-ikemoto** [comment]
＞I think you can point to the older version, I'm tired of doing this.

I see.

**Pull request merged**
