### PR TITLE
Update linear_percent_indicator.dart

### PR DESCRIPTION
**Pull request by superciccio**
add option to restart animation

### CODE REVIEW

**Comment by diegoveloper** [comment]
awesome :), would you mind creating a new sample using that new field?  I mean adding a new item inside `SampleCircularPage` and `SampleLinearPage` ?

**Comment by superciccio** [comment]
ok no prob !

**Comment by superciccio** [comment]
done :)

**Comment by diegoveloper** [comment]
thanks bro :D

**Pull request merged**
