### PR TITLE
Added Half Arc for Circular Percent Circular Percent Indicator

### PR DESCRIPTION
**Pull request by Vivek0004**
When User Chooses to Use HALF Arc Type, there will be a proper Half Arc behind the progress bar
Closes: #98

### CODE REVIEW

**Review by diegoveloper — CHANGES_REQUESTED** [review]
Please add a new sample in the file `sample_circular_page.dart` using this particular case, avoid breaking other samples.

Is this an optional value? what's the param name?

**Comment by Vivek0004** [comment]
Actually i didn't introduced any new Param, i just use if condition to ArcType , if ArcType goes to half then the background  circle also becomes an Arc, This looks like as a border to the Arc, if background color is defined

**Comment by diegoveloper** [comment]
> Actually i didn't introduced any new Param, i just use if condition to ArcType , if ArcType goes to half then the background circle also becomes an Arc, This looks like as a border to the Arc, if background color is defined

Ok, can you add a sample using that change?

**Comment by Vivek0004** [comment]
Added Sample

**Comment by diegoveloper** [comment]
One more thing before merging. Can you attach a picture Before and After the change (the sample)? . Thanks

**Comment by Vivek0004** [comment]
### Before Changes
Screenshot (402)
### After Changes
Screenshot (400)

**Pull request merged**
