### PR TITLE
Added new arcType and fixed margin when widget percent is 1.0

### PR DESCRIPTION
**Pull request by chrizstone**

### CODE REVIEW

**Comment by diegoveloper** [comment]
Can you provide a couple of screenshots about the current samples (to check if this change break anything) and your new sample.

**Comment by chrizstone** [comment]
Sure... See attached screens...
screen
screen2

**Comment by diegoveloper** [comment]
just a minor thing, can you attach a before/after image of the bug you fixed? (margin), and try on some different screen size devices/simulator.

**Comment by chrizstone** [comment]
Before:
screen3

After:
screen4

**Comment by diegoveloper** [comment]
Thanks for the contribution

**Pull request merged**
