### PR TITLE
Add an 'initialPercent' field to control the initial animation.

### PR DESCRIPTION
**Pull request by Erfa**

### CODE REVIEW

**Comment by diegoveloper** [comment]
Isn't the same to use just 'percent' ?

**Comment by Erfa** [comment]
As far as I can tell, the animation always starts at zero currently. This allows customizing that. If there are other ways to achieve that I'm open to it.

**Comment by diegoveloper** [comment]
Oh, so you don't want just the initial animation, right? Or you want to disable the entire animation of the widget.

**Comment by Erfa** [comment]
Yes, I just want to disable the initial animation. I.e. if I set it to 50% it should start there, without animation. If I later set it to 100% it should animate up there. 

I think animating up from zero is a nice default, but in my use case it made the UI a bit confusing.

**Comment by diegoveloper** [comment]
hmm I don't want to mess people with the values, so maybe you could create a bool flag like this : 

https://github.com/diegoveloper/flutter_percent_indicator/blob/9ce1946f1daa2fd5212712d36964b82b673315bd/lib/linear_percent_indicator.dart#L68 .

final bool animateFromInitialValue; 

and mark true by default

**Comment by Erfa** [comment]
I think animate _to_ initial percent makes a bit more sense in that case, since you're toggling the animation to the initially supplied percent value. Updated with that, seems to work well!

**Review by diegoveloper — APPROVED** [review]
great, thanks for the contribution

**Pull request merged**
