### PR TITLE
Added optional backgroundWidth

### PR DESCRIPTION
**Pull request by CircuitGuy**
Implements feature request #62 
The backgroundWidth property can be used to make a thinner 'remaining'
bar or a thicker border

Example with thicker background:

Example with thinner background:

### CODE REVIEW

**Comment by diegoveloper** [comment]
Great, just a few changes. Point the PR to dev instead of master, and add some examples in the sample file of the circular percent indicator.

**Comment by diegoveloper** [comment]
And don't forget to pull the data from master first. Master was updates.

**Comment by CircuitGuy** [comment]
@diegoveloper Great, will do.  Should be ~24 hours.

**Comment by CircuitGuy** [comment]
You know... 24 hours, 5 days, whatever.  I'm apparently now making the same estimate ratio for open source contributions as I take on my day job

**Pull request merged**
